#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}
# ──────────────────────────────────────────────────────────────────────────
# STAGES — the steps only a human can take when adopting cozyplan in a repo.
# Everything a command can do is done by `plan_tool init`; this wizard covers
# the rest and the one call that needs repo admin.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/plan_tool.py"
PY="$(command -v python3 || command -v python)"

banner "Adopt cozyplan in this repo"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "cozyplan needs python3 and git. gh is optional: without it, issues queue"
say "to .scratch/ and replay later."
[[ -n "$PY" ]] && step "python3 — $("$PY" -V 2>&1)" || { warn "python3 not found. Install it, then re-run."; exit 1; }
step "git — $(git --version)"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  step "gh — authenticated as $(gh api user --jq .login 2>/dev/null || echo '?')"
  HAVE_GH=1
else
  warn "gh missing or not authenticated. Stage 6 will give you the click path instead."
  note "To fix later: brew install gh && gh auth login"
  HAVE_GH=0
fi
[[ -f "$PT" ]] || { warn "plan_tool.py not found beside this script ($PT)"; exit 1; }
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Identify the repo"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { warn "Not a git repository. Run this inside the repo you are adopting."; exit 1; }
ORIGIN="$(git remote get-url origin 2>/dev/null || true)"
if [[ -n "$ORIGIN" ]]; then
  REPO_SLUG="$(printf '%s' "$ORIGIN" | sed -E 's#.*[:/]([^/:]+/[^/]+?)(\.git)?$#\1#')"
  step "origin — $ORIGIN"
  step "slug   — $REPO_SLUG"
else
  warn "No origin remote. The issue-tracker adapter needs the slug to point at the right repo."
  ask REPO_SLUG "Repo slug (owner/name):"
fi
BRANCH="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || echo main)"
step "default branch — $BRANCH"
confirm "Adopt cozyplan in this repo?" || { say "Nothing changed."; exit 0; }

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Wire the repo"
say "This creates the records, the event log, SYSTEM.md, STATE.md, CLAUDE.md,"
say "the tracked git hooks, and the CI workflow. It never overwrites your content."
say "--vendor also commits the skills into .claude/skills/, so your teammates"
say "clone and install nothing at all."
if confirm "Vendor the skills into this repo (recommended for teams)?"; then
  VENDOR="--vendor"
else
  VENDOR=""
  note "Without --vendor each teammate installs the plugin themselves."
fi
"$PY" "$PT" init --root . --repo "$REPO_SLUG" $VENDOR
pause "Read the report above, then press Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Review and commit"
say "Everything above is a normal tracked file. Review before committing."
git status --short | sed 's/^/  /'
confirm "Commit these?" || { say "Left uncommitted. Re-run when you are ready."; exit 0; }
git add -A
git commit -q -m "chore: adopt cozyplan

Wired with plan_tool init. STATE.md is generated from docs/state.ndjson;
never hand-edit it. Run plan_tool doctor to see what is wired in a clone."
step "committed"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Push"
say "Pushing publishes the wiring and triggers the CI check for the first time."
say "A check cannot be marked required until it has reported at least once."
confirm "Push to origin/$BRANCH?" || { say "Not pushed. Re-run this wizard after you push."; exit 0; }
git push -u origin "$BRANCH"
step "pushed"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Wait for the first CI run"
if [[ "$HAVE_GH" == "1" ]]; then
  say "Waiting for the state-check workflow to report..."
  for _ in $(seq 1 30); do
    CONCLUSION="$(gh run list --branch "$BRANCH" --workflow "state check" --limit 1 --json conclusion --jq '.[0].conclusion' 2>/dev/null || true)"
    [[ -n "$CONCLUSION" && "$CONCLUSION" != "null" ]] && break
    sleep 10
  done
  if [[ "$CONCLUSION" == "success" ]]; then
    step "state-check passed"
  else
    warn "The first run did not pass (conclusion: ${CONCLUSION:-none yet})."
    say "Inspect it with: gh run view --log-failed"
    confirm "Continue anyway?" || exit 0
  fi
else
  open_url "https://github.com/$REPO_SLUG/actions"
  step "Wait for the 'state check' workflow to finish."
  pause "Press Enter once it has reported"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Mark the check required"
say "This is the step that turns CI from reporting into gating. Until it is done,"
say "the check runs and nobody has to listen to it."
say ""
say "It changes repository settings, so it needs admin on $REPO_SLUG."
if [[ "$HAVE_GH" == "1" ]] && gh api "repos/$REPO_SLUG" --jq '.permissions.admin' 2>/dev/null | grep -q true; then
  if gh api "repos/$REPO_SLUG/branches/$BRANCH/protection" >/dev/null 2>&1; then
    warn "$BRANCH already has a protection rule."
    warn "Setting it here REPLACES the whole rule, including settings this wizard does not manage."
    say "Safer to edit it by hand:"
    open_url "https://github.com/$REPO_SLUG/settings/branches"
    step "Edit the rule for '$BRANCH' → Require status checks to pass → add 'state-check'."
    pause "Press Enter when saved"
  else
    STRICT=false
    confirm "Also require branches to be up to date before merging? (stricter, more rebasing)" && STRICT=true
    if confirm "Mark 'state-check' required on $BRANCH now?"; then
      gh api -X PUT "repos/$REPO_SLUG/branches/$BRANCH/protection" --input - >/dev/null <<JSON
{
  "required_status_checks": { "strict": $STRICT, "contexts": ["state-check"] },
  "enforce_admins": false,
  "required_pull_request_reviews": null,
  "restrictions": null
}
JSON
      step "state-check is now required on $BRANCH"
    else
      say "Skipped. The click path is below whenever you want it."
      open_url "https://github.com/$REPO_SLUG/settings/branches"
    fi
  fi
else
  say "Doing it by hand:"
  open_url "https://github.com/$REPO_SLUG/settings/branches"
  step "Click 'Add branch protection rule' (or edit the existing one)."
  step "Branch name pattern: $BRANCH"
  step "Tick 'Require status checks to pass before merging'."
  step "In the search box that appears, type 'state-check' and select it."
  step "Click 'Create' or 'Save changes' at the bottom."
  note "The check must have reported at least once or it will not appear in that list."
  pause "Press Enter when saved"
fi

# ── close ─────────────────────────────────────────────────────────────────
stage "Verify"
"$PY" "$PT" doctor --root . || true
say ""
if [[ "$HAVE_GH" == "1" ]] && gh api "repos/$REPO_SLUG/branches/$BRANCH/protection" --jq '.required_status_checks.contexts[]' 2>/dev/null | grep -q state-check; then
  step "confirmed: state-check is required on $BRANCH"
else
  warn "state-check is not required yet — doctor will keep saying so."
fi
say ""
say "Teammates clone and run nothing. On their first session the agent reads"
say "CLAUDE.md, runs doctor, and wires the local git hooks if they are missing."

finish
